// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace PetClinic.ApiTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("OwnersApiTests")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class OwnersApiTestsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "OwnersApiTests", "Validate Owners API endpoints", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "OwnersApiTests.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/OwnersApiTests.feature.ndjson", 42);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Get all owners returns a list of valid owners")]
        [global::NUnit.Framework.CategoryAttribute("OwnersApi")]
        public async global::System.Threading.Tasks.Task GetAllOwnersReturnsAListOfValidOwners()
        {
            string[] tagsOfScenario = new string[] {
                    "OwnersApi"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get all owners returns a list of valid owners", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync("I make a get request to owners endpoint", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
 await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 9
 await testRunner.AndAsync("the response content type should be \"application/json\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
 await testRunner.AndAsync("owners response should contain non-empty list of owners", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
 await testRunner.AndAsync("each owner in the list should have valid data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Create a pet for an existing owner and verify persistence")]
        [global::NUnit.Framework.CategoryAttribute("OwnersApi")]
        [global::NUnit.Framework.CategoryAttribute("CreatePet")]
        [global::NUnit.Framework.CategoryAttribute("E2E")]
        [global::NUnit.Framework.CategoryAttribute("CleanupPet")]
        public async global::System.Threading.Tasks.Task CreateAPetForAnExistingOwnerAndVerifyPersistence()
        {
            string[] tagsOfScenario = new string[] {
                    "OwnersApi",
                    "CreatePet",
                    "E2E",
                    "CleanupPet"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create a pet for an existing owner and verify persistence", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 15
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
 await testRunner.GivenAsync("I make a get request to owners endpoint", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 17
 await testRunner.AndAsync("I select an existing owner from the response", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
 await testRunner.AndAsync("I make a get request to pet types endpoint", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
 await testRunner.AndAsync("I select an existing pet type from the response", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
 await testRunner.WhenAsync("I make a post request to create a pet for the selected owner with valid data", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
 await testRunner.ThenAsync("the response status code should be 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 22
 await testRunner.AndAsync("the response content type should be \"application/json\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
 await testRunner.AndAsync("the created pet response should contain valid pet data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
 await testRunner.AndAsync("I make a get request to retrieve the created pet by its ID and owner ID", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
 await testRunner.AndAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
 await testRunner.AndAsync("the retrieved pet matches the created pet data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Add a pet to a newly created owner and verify persistence")]
        [global::NUnit.Framework.CategoryAttribute("OwnersApi")]
        [global::NUnit.Framework.CategoryAttribute("CreateOwner")]
        [global::NUnit.Framework.CategoryAttribute("CreatePet")]
        [global::NUnit.Framework.CategoryAttribute("E2E")]
        [global::NUnit.Framework.CategoryAttribute("CleanupPet")]
        [global::NUnit.Framework.CategoryAttribute("CleanupOwner")]
        public async global::System.Threading.Tasks.Task AddAPetToANewlyCreatedOwnerAndVerifyPersistence()
        {
            string[] tagsOfScenario = new string[] {
                    "OwnersApi",
                    "CreateOwner",
                    "CreatePet",
                    "E2E",
                    "CleanupPet",
                    "CleanupOwner"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Add a pet to a newly created owner and verify persistence", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 31
 await testRunner.GivenAsync("I create a new owner successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 32
 await testRunner.AndAsync("I make a get request to pet types endpoint", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
 await testRunner.AndAsync("I select an existing pet type from the response", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
 await testRunner.WhenAsync("I make a post request to create a pet for the newly created owner with valid data" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
 await testRunner.ThenAsync("the response status code should be 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 36
 await testRunner.AndAsync("the response content type should be \"application/json\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
 await testRunner.AndAsync("the created pet response should contain valid pet data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
 await testRunner.AndAsync("I make a get request to retrieve the created pet by its ID and created owner ID", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
 await testRunner.AndAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
 await testRunner.AndAsync("the retrieved pet matches the created pet data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify a user is not able to register an owner with missing mandatory fields")]
        [global::NUnit.Framework.CategoryAttribute("OwnersApi")]
        [global::NUnit.Framework.CategoryAttribute("Validation")]
        public async global::System.Threading.Tasks.Task VerifyAUserIsNotAbleToRegisterAnOwnerWithMissingMandatoryFields()
        {
            string[] tagsOfScenario = new string[] {
                    "OwnersApi",
                    "Validation"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify a user is not able to register an owner with missing mandatory fields", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 44
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 45
 await testRunner.GivenAsync("I make a post request to owners endpoint with empty mandatory fields", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 46
 await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "ErrorMessage",
                            "# Field"});
                table1.AddRow(new string[] {
                            "size must be between 1 and 30",
                            "firstName and lastName"});
                table1.AddRow(new string[] {
                            "must match",
                            "lastName"});
                table1.AddRow(new string[] {
                            "size must be between 1 and 255",
                            "address"});
                table1.AddRow(new string[] {
                            "size must be between 1 and 80",
                            "city"});
                table1.AddRow(new string[] {
                            "size must be between 1 and 20",
                            "telephone"});
#line 47
 await testRunner.AndAsync("response should contain error messages:", ((string)(null)), table1, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify a user is not able to register an owner with invalid details")]
        [global::NUnit.Framework.CategoryAttribute("OwnersApi")]
        [global::NUnit.Framework.CategoryAttribute("Validation")]
        [global::NUnit.Framework.TestCaseAttribute("Telephone", "", "size must be between 1 and 20", "400", "Empty", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("Telephone", "1", "Phone number must be exactly 10 digits", "500", "1 digit", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("Telephone", "123456", "Phone number must be exactly 10 digits", "500", "6 digits", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("Telephone", "12345678901234567890", "Phone number must be exactly 10 digits", "500", "20 digits", "7", null)]
        [global::NUnit.Framework.TestCaseAttribute("Telephone", "123456789012345678901", "size must be between 1 and 20", "400", "21 digits", "8", null)]
        [global::NUnit.Framework.TestCaseAttribute("Telephone", "AbcdePhone", "must match", "400", "10 letters", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("Telephone", "!@#$%^-&*?", "must match", "400", "special characters", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("FirstName", "", "size must be between 1 and 30", "400", "Empty", "11", null)]
        [global::NUnit.Framework.TestCaseAttribute("FirstName", "AAAAAAAAAAbbbbbbbbbbccccccccccd", "size must be between 1 and 30", "400", "31 letter", "12", null)]
        [global::NUnit.Framework.TestCaseAttribute("FirstName", "Mary‑Jane", "must match", "400", "Hyphenated name", "13", null)]
        [global::NUnit.Framework.TestCaseAttribute("FirstName", "Maria!$%", "must match", "400", "special characters", "14", null)]
        [global::NUnit.Framework.TestCaseAttribute("FirstName", "Iskra123", "must match", "400", "letters and digits", "15", null)]
        [global::NUnit.Framework.TestCaseAttribute("LastName", "", "size must be between 1 and 30", "400", "Empty", "16", null)]
        [global::NUnit.Framework.TestCaseAttribute("LastName", "AAAAAAAAAAbbbbbbbbbbccccccccccD", "size must be between 1 and 30", "400", "31 letter", "17", null)]
        [global::NUnit.Framework.TestCaseAttribute("LastName", "Gray‑Stone", "must match", "400", "Hyphenated name", "18", null)]
        [global::NUnit.Framework.TestCaseAttribute("LastName", "Smith#@!", "must match", "400", "special characters", "19", null)]
        [global::NUnit.Framework.TestCaseAttribute("LastName", "Davis123", "must match", "400", "letters and digits", "20", null)]
        [global::NUnit.Framework.TestCaseAttribute("City", "", "size must be between 1 and 80", "400", "Empty", "21", null)]
        [global::NUnit.Framework.TestCaseAttribute("City", "LONG_81", "size must be between 1 and 80", "400", "81 letter", "22", null)]
        [global::NUnit.Framework.TestCaseAttribute("Address", "", "size must be between 1 and 255", "400", "Empty", "23", null)]
        [global::NUnit.Framework.TestCaseAttribute("Address", "LONG_256", "size must be between 1 and 255", "400", "256 letter", "24", null)]
        public async global::System.Threading.Tasks.Task VerifyAUserIsNotAbleToRegisterAnOwnerWithInvalidDetails(string field, string value, string message, string statusCode, string description, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "OwnersApi",
                    "Validation"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("field", field);
            argumentsOfScenario.Add("value", value);
            argumentsOfScenario.Add("message", message);
            argumentsOfScenario.Add("statusCode", statusCode);
            argumentsOfScenario.Add("#Description", description);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify a user is not able to register an owner with invalid details", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 57
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 58
 await testRunner.GivenAsync(string.Format("I make a post request to owners endpoint with not valid details for \"{0}\" with \"{" +
                            "1}\"", field, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 59
 await testRunner.ThenAsync(string.Format("the response status code should be {0}", statusCode), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 60
 await testRunner.AndAsync(string.Format("the response should contain the following error message \"{0}\"", message), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify a user is able to register an owner with specific details")]
        [global::NUnit.Framework.CategoryAttribute("OwnersApi")]
        [global::NUnit.Framework.CategoryAttribute("Validation")]
        [global::NUnit.Framework.CategoryAttribute("CreateOwner")]
        [global::NUnit.Framework.CategoryAttribute("CleanupOwner")]
        [global::NUnit.Framework.TestCaseAttribute("FirstName", "Искра", "Cyrillic letters", "25", null)]
        [global::NUnit.Framework.TestCaseAttribute("FirstName", "A", "1 letter", "26", null)]
        [global::NUnit.Framework.TestCaseAttribute("FirstName", "AAAAAAAAAAbbbbbbbbbbcccccccccc", "30 letters", "27", null)]
        [global::NUnit.Framework.TestCaseAttribute("LastName", "Кръстева", "Cyrillic letters", "28", null)]
        [global::NUnit.Framework.TestCaseAttribute("LastName", "a", "1 letter", "29", null)]
        [global::NUnit.Framework.TestCaseAttribute("LastName", "aaaaaaaaaabbbbbbbbbbcccccCCCCC", "30 letters", "30", null)]
        [global::NUnit.Framework.TestCaseAttribute("City", "Frankfurt‑Oder", "Hyphenated city", "31", null)]
        [global::NUnit.Framework.TestCaseAttribute("City", "O\'ConnorTown", "Apostrophe", "32", null)]
        [global::NUnit.Framework.TestCaseAttribute("City", "София", "Cyrillic letters", "33", null)]
        [global::NUnit.Framework.TestCaseAttribute("City", "Tokyo123", "Letters and digits", "34", null)]
        [global::NUnit.Framework.TestCaseAttribute("City", "Madrid!@#", "Special characters", "35", null)]
        [global::NUnit.Framework.TestCaseAttribute("City", "a", "1 letter", "36", null)]
        [global::NUnit.Framework.TestCaseAttribute("City", "LONG_80", "80 letters", "37", null)]
        [global::NUnit.Framework.TestCaseAttribute("Address", "b", "1 letter", "38", null)]
        [global::NUnit.Framework.TestCaseAttribute("Address", "LONG_255", "255 letters", "39", null)]
        public async global::System.Threading.Tasks.Task VerifyAUserIsAbleToRegisterAnOwnerWithSpecificDetails(string field, string value, string description, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "OwnersApi",
                    "Validation",
                    "CreateOwner",
                    "CleanupOwner"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("field", field);
            argumentsOfScenario.Add("value", value);
            argumentsOfScenario.Add("#Description", description);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify a user is able to register an owner with specific details", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 89
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 90
 await testRunner.GivenAsync(string.Format("I make a post request to owners endpoint with valid specific details for \"{0}\" wi" +
                            "th \"{1}\"", field, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 91
 await testRunner.ThenAsync("the response status code should be 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 92
 await testRunner.AndAsync("the created owner persists with the provided details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
