name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start containers
      run: docker compose up -d

    - name: Wait for services to be ready
      run: sleep 15

    # Install Google Chrome
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg unzip curl
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    # Install matching ChromeDriver
    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | sed 's/Google Chrome //')
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
        wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Run all tests (UI + API)
      run: dotnet test --logger "trx;LogFileName=test-results.trx"

    - name: Debug TRX files
      run: find . -type f -name "*.trx" -print

    # Install ReportGenerator
    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    # Generate combined HTML report for ALL TRX files
    - name: Generate HTML report
      run: reportgenerator -reports:**/TestResults/**/test-results.trx -targetdir:TestReports/Html -reporttypes:Html

    # Upload TRX files
    - name: Upload TRX results
      uses: actions/upload-artifact@v4
      with:
        name: all-test-results-trx
        path: "**/TestResults/**/test-results.trx"

    # Upload HTML report
    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: all-test-results-html
        path: TestReports/Html

    - name: Stop containers
      if: always()
      run: docker compose down
